# Generated by Django 3.2.7 on 2021-09-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_task', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField()),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
